'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MembershipType
    Public Property SingupFree As Integer
    Public Property DurationlnMonths As Integer
    Public Property DiscountRate As Integer
    Public Property Id As Integer
    Public Property MembershipName As String

    Public Overridable Property Customer As ICollection(Of Customer) = New HashSet(Of Customer)

End Class
