'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class vidly2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=vidly2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Customer() As DbSet(Of Customer)
    Public Overridable Property MembershipType() As DbSet(Of MembershipType)
    Public Overridable Property Movie() As DbSet(Of Movie)
    Public Overridable Property Rents() As DbSet(Of Rents)
    Public Overridable Property Users() As DbSet(Of Users)

End Class
