'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Users
    Public Property Id As Integer
    Public Property Correo As String
    Public Property Clave As String
    Public Property Perfil As String
    Public Property Idastate As Nullable(Of Integer)

    Public Overridable Property Rents As ICollection(Of Rents) = New HashSet(Of Rents)

End Class
