'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rents
    Public Property Id As Integer
    Public Property IdMovie As Integer
    Public Property IdCustomer As Integer
    Public Property IdUser As Integer
    Public Property DateRental As Date
    Public Property DateDevol As Nullable(Of Date)
    Public Property Returned As Nullable(Of Boolean)
    Public Property Description As String

    Public Overridable Property Customer As Customer
    Public Overridable Property Movie As Movie
    Public Overridable Property Users As Users

End Class
